name: 🐛 Bug Report For PrismarineJS Website
description: Report an issue if something isn't working as expected 🤔.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for wanting to report an issue you've found on the PrismarineJS website.
        Please fill in the template below. If unsure about something, just do as best
        as you're able. If you are reporting a visual glitch, it will be much easier
        for us to fix it when you attach a screenshot as well.
  - type: input
    attributes:
      label: 'URL:'
      description: The URL of the page you are reporting an issue on.
      placeholder: https://prismarine.js.org/
    validations:
      required: true
  - type: input
    attributes:
      label: 'Browser Name:'
      description: What kind of browser are you using?
      placeholder: Safari
    validations:
      required: true
  - type: input
    attributes:
      label: 'Browser Version:'
      description: What version of browser are you using?
      placeholder: '16.0.0'
    validations:
      required: true
  - type: input
    attributes:
      label: 'Operating System:'
      description: What operating system are you using
        (Write it in full, with version number)?
      placeholder: 'Macos'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Description:'
      placeholder: |
        Some text here
    validations:
      required: true
